name: paddleocr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - dlib
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
      - paddleocr==2.6
      - paddlepaddle==3.0.0
      - opencv-python==4.11.0.86
      - opencv-contrib-python==4.11.0.86
      - flask
      - flask-babel
      - fastapi
      - uvicorn
      - scikit-image
      - imageio
      - shapely
      - lmdb
      - imgaug
      - python-dotenv
      - pycryptodome
      - pydantic
      - pydantic-settings
      - requests
      - python-multipart
      - rarfile
      - openpyxl
      - premailer
      - lxml
      - pefile
      - visualdl
      - jinja2
